nelmio_cors:
    defaults:
            allow_credentials: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)']
            allow_methods: ['GET', 'POST','PUT','DELETE','OPTIONS','PATCH']
            allow_headers: ['Content-Type','Authorization']
            expose_headers: ['Link']
            max_age: 3600           
    paths:
        '^/':~
